### PR TITLE
Add compare.c to get latest commits

### PR DESCRIPTION
**Pull request by KayGau**

### CODE REVIEW

**Comment by audrism** [comment]
@KayGau, the code does not appear to fetch from the remote repository? Am I missing something?

**Comment by KayGau** [comment]
Oh, yes. I just write a function to get new commits. I will add the fetch operation later.

**Comment by audrism** [comment]
These are existing commits that are already in the repository, not new commits?

**Comment by KayGau** [comment]
I want to test if the algorithm can correctly get commits between two HEADs. So I chose two commits in the repository as two HEAD.
I think what I need to do is:
Compare two HEADs. if they are different, then fetch the remote repository and merge it with local.
Then in the new repository, use the algorithm above to get new commits.
I am not sure if I correctly understand the need?

**Comment by KayGau** [comment]
I am sorry that I am not familiar with libgit2. I looked at the API about the fetch operation in libgit2 just now. I think what I did is complicate. I think I only need to fetch, and then can get new commits. I'll write another version as soon as possible.

**Comment by audrism** [comment]
If the repo is cloned there is no need to fetch. 

The challenge is to fetch without first cloning or even having the actual 
local repo.

The sequence of commits that are missing is obtained by the remote repo.

To understand how the fetch protocol works its probably best to instrument 
the code and also use strace/ptrace.  

get_last.c provides an example with the extra function git_get_last
added that simulates a part of the fetch protocol where the latest head of the remote is obtained.

**Pull request merged**
